package com.cgbros.silkhub

enum class Job {

    FLEECA_JOB, PRISON_BREAK, HUMANE_LABS_RAID, SERIES_A_FUNDING, PACIFIC_STANDARD_JOB,
    CEO_MISSIONS, BIKER_MISSIONS, BUNKER_MISSIONS, HANGAR_MISSIONS

}
